services:
  qdrant:
    container_name: dblab3_qdrant
    image: qdrant/qdrant:v1.7.2
    ports:
      - 6333:6333
  jupyter:
    build:
      context: docker
      dockerfile: Dockerfile.jupyter
    container_name: dblab3_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./lab:/opt/app/data:rw
