FROM quay.io/jupyter/base-notebook:lab-4.0.9

USER root

RUN apt-get update && apt-get -y install build-essential cmake

USER 1000

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--port=8888", "--no-browser","--NotebookApp.token=''","--NotebookApp.password=''", "--notebook-dir=/opt/app", "--LabApp.default_url='/lab/tree/data/lab-qdrant-intro.ipynb'"]
